version: '2'

services:
  digdag:
    build: .
    container_name: digdag
    command: server -m -b 0.0.0.0
    volumes:
      - ./src:/src
    ports:
      - "65432:65432"
    links:
      - postgresql
  postgresql:
    image: postgres:9.5-alpine
    container_name: digdag-db
    volumes:
      - digdag-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  digdag-db:
    driver: local